### PR TITLE
Python 2.4 support (formerly RPM support)

### PR DESCRIPTION
**Pull request by kmcfate**
Adds Base and Core comps groups to ignore list with all deps. Plus supports config file modification based on rpm --verify.

Feedback encouraged!

(Edit 2011-03-29 10:30pm: rcrowley changed title.)

### CODE REVIEW

**Comment by rcrowley** [comment]
I cherry-picked a couple of your commits to build the RPM and RPM exclusion support.  I've got some research and experimentation to do before I merge the legacy support you added here.  Thanks!

**Comment by kmcfate** [comment]
Not a problem. I manage a few thousand systems with a few dozen
configurations with puppet and would love to have this workable on my RHEL 5
boxes (and it nearly is.) I'll keep going with what I have and see how
things turn out. I'd like to see some exclusions from the ruby/php/python
lists of items already managed as system packages. Plus the puppet manifest
generation has some problems with quoting. Those are the next 2 things I am
looking at.

--Kal

**Comment by rcrowley** [comment]
The quoting should be fixed by d27aa8d6ac631b3f4b67f1ebf9374af9bbd6ed21.

**Comment by rcrowley** [comment]
I've just opened a topic on the mailing list explaining that Python 2.4 support will not be merged.  https://groups.google.com/forum/#!topic/blueprint-dev/mjLKgxl2vJw

**Pull request closed without merging**
